spring.application.name=NSQL

gemini.model.name=gemini-3.1-flash-lite-preview

spring.datasource.url=jdbc:mysql://mysql.cs.bangor.ac.uk:3306/dreamhome?serverTimezone=Europe/London
spring.datasource.username=sps24fjb
spring.datasource.driver=com.mysql.cj.jdbc.Driver